### ISSUE TITLE
specifiying different output folder for "WEB" image

### ISSUE THREAD

**Issue by joreilly** [muzzley/mobile-icon-resizer#13]
I'm currently running this for Android project and am settings `androidOutputFolder` to something like `app/src/main/res`.  The app launcher icons are generated and stored in this location....however so to is the WEB image (which is used only for Play Store).  When I build app then I get following.  Would it make sense to be able to specify different output folder for that image (can fix this manually but am trying to automate this through script).

res/WEB/ic_launcher.png:1:1: Error: Content is not allowed in prolog

**Comment by joreilly** [comment]
My solution for now is to run this twice with 2 different config files....one without "WEB" (that has output folder of `app/src/main/res`) and another that just has "WEB" (with output folder pointing to  location that fastlane supply will use to upload to play store).

**Comment by tiagoalves** [comment]
You can specify relative paths in the `folder` properties of the configuration file.

So, you could specify something like:

```
  android: {
    "images" : [
      // ...
      {
        // Image to upload to the Play Store
        "size": "512x512",
        "folder" : "../../../../WEB"
      }
    ]
  }
```

In this case, you will end up with a base folder `app/` (as per your example) and a folder `WEB/` in the root of your output directory.

Does this solve your issue?
