### ISSUE TITLE
Unsafe use of eval

### ISSUE THREAD

**Issue by cristianstaicu** [muzzley/mobile-icon-resizer#8]
The following use of eval in the file lib/resize.js is unsafe:
```js
function getSizeFromRatio(options) {
    var ratio = eval(options.ratio);
    return Math.floor(options.size * ratio);
}
```

Since the ratio is a parameter passed to your module, the clients of your libary are not aware of these dangers and may allow arbitrary user input. I suggest refactoring out eval, parse the user input or use a sanitization module like: 
https://www.npmjs.com/package/eval-sanitizer

**Comment by tiagoalves** [comment]
Thank you for bringing this up. I've just changed that particular code to use [math.js](http://mathjs.org/)'s eval:

`math.eval()`

Also published v0.4.3 to npm.
